services:
  db:
    image: postgres:16
    container_name: portaria_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: portaria
      POSTGRES_USER: portaria_user
      POSTGRES_PASSWORD: portaria_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: